#!/bin/bash
set -euo pipefail

# usage:
# ./certgen <cert_filename> <domain>
#
# if domain is '*' then wildcard cert is generated for a few TLD


certname=$1
domain=$2

mkdir new_cert
cd new_cert

if [[ "${domain}" == '*' ]]; then
  alt_name='subjectAltName = DNS:*.lan,DNS:*.com,DNS:*.org,DNS:*.net'
else
  alt_name="subjectAltName = DNS:${domain}"
fi

# more info in `man req`
openssl req \
  -batch \
  -subj "/C=PL/CN=${certname}" \
  -addext "${alt_name}" \
  -nodes \
  -newkey rsa:2048 \
  -x509 \
  -days 3650 \
  -keyout ${certname}.key \
  -out ${certname}.crt

cat ${certname}.crt ${certname}.key > ${certname}.pem
chmod 600 ${certname}.pem
openssl x509 -in ${certname}.pem -pubkey -noout > ${certname}.pub

