#!/bin/bash
set -euo pipefail


usage() {
  echo "usage: dev_install [ARGS]

-t, --target <path>   path to target disk device, existing LVM volume group
                      name, image file, or rootfs directory
-i, --iface           interface for default gateway
-s, --static-ip       use static ip (with netmask suffix), instead of dhcp
-g, --static-gw       use static gateway ip
-d, --dns-server      dns server address
-l, --label           prefix for LVM logical volumes, partitions, encrypted
                      devices, and filesystems; also a hostname
-k, --public-key      path to a public ssh key file to include in image
-y, --yes             don't ask for permission to continue

--encrypt-home        encrypt home partition
--encrypt-root        encrypt whole root partition
-p, --purge-all       remove all existing partitions from device (default is to
                      create new partitions on existing free disk space)
-e, --efi, --uefi     force uefi install

--uri                 uri for apt package download
--suite               suite of apt packages to download

-b, --boot-size       boot partition size
-r, --root-size       root partition size
-u, --home-size       user home partition size (omit if not defined)
-v, --var-size        var partition size (omit if not defined)

--boot-part           existing boot partition path to utilize
--root-part           existing root partition path to utilize
--home-part           existing home partition path to utilize
--var-part            existing var partition path to utilize

--raid                install on existing raid partitions
--skip-unmount        do not unmount and do not close disks after the install

--examples            print examples of usage
--raid-example        print example of raid installation
--help                this help message
"
  exit 0
}

examples() {
  echo "examples:
# install all deps
apt install uuid-runtime gdisk parted debootstrap mkfs.ext4 perl-base dosfstools

# install and purge existing disk
./debian_installer -t /dev/sdz -l main -i enp1s0 -k ~/.ssh/authorized_keys -b 512M -r 64G -u 32G -v 32G -p

# install on existing partitions
./debian_installer -l main -i enp1s0 -k ~/.ssh/authorized_keys --boot-part=/dev/sdz1 --root-part=/dev/sdz2

# create a vm
./debian_installer -t ./vm.img -l main -i enp1s0 -k ~/.ssh/authorized_keys -b 128M -r 4G
"
  exit 0
}

raid_example() {
  echo '
disk1="/dev/nvme0n1"
disk2="/dev/nvme1n1"
boot_size="1024M"
root_size="64G"
var_size="128G"
lvm_size="700G"
sgdisk --zap-all "${disk1}"
sgdisk --zap-all "${disk2}"
partprobe
sgdisk --new "1::+${boot_size}" "${disk1}"
sgdisk --new "1::+${boot_size}" "${disk2}"
sgdisk --new "2::+${root_size}" "${disk1}"
sgdisk --new "2::+${root_size}" "${disk2}"
sgdisk --new "3::+${var_size}" "${disk1}"
sgdisk --new "3::+${var_size}" "${disk2}"
sgdisk --new "4::+${lvm_size}" "${disk1}"
sgdisk --new "4::+${lvm_size}" "${disk2}"
partprobe
mdadm --create /dev/md/boot --homehost=srv --level=1 --raid-devices=2 --metadata 1.0 ${disk1}p1 ${disk2}p1
mdadm --create /dev/md/root --homehost=srv --level=1 --raid-devices=2 --metadata 1.2 ${disk1}p2 ${disk2}p2
mdadm --create /dev/md/var  --homehost=srv --level=1 --raid-devices=2 --metadata 1.2 ${disk1}p3 ${disk2}p3
mdadm --create /dev/md/lvm  --homehost=srv --level=1 --raid-devices=2 --metadata 1.2 ${disk1}p4 ${disk2}p4
./debian_installer -l srv -i enp65s0 -k ~/.ssh/authorized_keys --boot-part /dev/md/boot --root-part /dev/md/root --var-part /dev/md/var --raid -e
'
  exit 0
}

# just a helper function defined early
err_exit() {
  printf 'ERROR: %s\n' "${1}"
  exit 1
}


# initilize global variables
# ==========================

# target - a path to the disk or file
DEV=

# main network interface
IFACE=

# static ip for the interface
STATIC_IP=

# static gateway ip for the interface
STATIC_GW=

# dns server address for resolv.conf
DNS_SERVER=

# public ssh key to put in authorized_hosts
PUB_SSH_FILE=

# don't ask to continue
YES=false

# encrypt the home partition
ENCRYPT_HOME=false

# encrypt the whole root partition
ENCRYPT_ROOT=false

# remove all existing partitions
PURGE=false

# force uefi
UEFI_FORCE=false

# installation on raid volumes
RAID=false

# do not unmount at the end of the script
SKIP_UNMOUNT=false

# size of partitions and total size
BOOT_SIZE=
ROOT_SIZE=
HOME_SIZE=
VAR_SIZE=
BOOT_SIZE_B=
ROOT_SIZE_B=
HOME_SIZE_B=
VAR_SIZE_B=
SIZE=

# path of existing partitions to use
GRUB_PART=
BOOT_PART=
ROOT_PART=
HOME_PART=
VAR_PART=
BOOT_PART=

# partition numbers
GRUB_PART_N=
BOOT_PART_N=
ROOT_PART_N=
HOME_PART_N=
VAR_PART_N=

# default path to mount partitions
ROOT_DIR=/tmp/deb_build

# tmp dir to extract files
readonly TMP_DIR='/tmp/deb_build_tmp'

# LV containing efi system partition
BOOT_DISK=

# type of the disk: 'device' (path to /dev/*), 'volume_group' (LVM volume group
# name), or 'file' (path to a regular file)
DEV_TYPE=

# bootloader install type: 'bios' 'or' 'uefi'
INST_TYPE=

# first free loop device to use for dev_type 'file'
LOOP_DEV=

# prefix for labeling partitions and filesystems
LABEL=

# label, but with dashes converted to underscores
LABEL_UNDER=

# dev mapper name for encrypted home or root
MAP_DEV=

command -v uuidgen >/dev/null || err_exit 'uuidgen from uuid-runtime missing'

# UUIDs for partitions to be created, either generated by the script or read
# from the sys config files
UUID_GRUB="$(uuidgen | sed 's|.*-.*-.*-.*-.\{4\}|00000000-0000-0000-0000-0000|')"
UUID_BOOT="$(uuidgen | sed 's|.*-.*-.*-.*-.\{4\}|00000000-0000-0000-0000-0000|')"
UUID_BOOT_FAT="$(rev <<< ${UUID_BOOT} | cut -c 1-8 | rev)"
UUID_ROOT="$(uuidgen | sed 's|.*-.*-.*-.*-.\{4\}|00000000-0000-0000-0000-0000|')"
UUID_HOME="$(uuidgen | sed 's|.*-.*-.*-.*-.\{4\}|00000000-0000-0000-0000-0000|')"
UUID_VAR="$(uuidgen | sed 's|.*-.*-.*-.*-.\{4\}|00000000-0000-0000-0000-0000|')"

# repositories for apt: main contrib non-free non-free-firmware
APT_REPOS='main'

# uri to fetch packages from (for kali: http://http.kali.org/kali)
URI='http://ftp.uk.debian.org/debian'

# suite of packages to get (for kali: kali-last-snapshot)
SUITE='bookworm'

# keys to verify packages
KEYRING='/usr/share/keyrings/debian-archive-keyring.gpg'


# parse args
# ==========

opts='t:i:s:g:d:l:k:yepuhb:r:v:'

long='target:,iface:,static-ip:,static-gw:,dns-server:,label:,public-key:,'
long+='yes,encrypt-home,encrypt-root,purge-all,efi,uefi,uri:,suite:,'
long+='boot-size:,root-size:,home-size:,var-size:,'
long+='boot-part:,root-part:,home-part:,var-part:,'
long+='raid,skip-unmount,help,examples,raid-example'

parsed_opts=$(getopt -o=${opts} --long=${long} --name "$0" -- "$@")

while [[ ${#} -gt 0 ]]; do
  key="${1}"
  case ${key} in
  -t | --target)
    readonly DEV="${2}"
    shift 2
    ;;
  -i | --iface)
    readonly IFACE="${2}"
    shift 2
    ;;
  -s | --static-ip)
    readonly STATIC_IP="${2}"
    shift 2
    ;;
  -g | --static-gw)
    readonly STATIC_GW="${2}"
    shift 2
    ;;
  -d | --dns-server)
    readonly DNS_SERVER="${2}"
    shift 2
    ;;
  -l | --label)
    readonly LABEL="${2}"
    readonly LABEL_UNDER="$(echo ${LABEL} | tr - _)"
    shift 2
    ;;
  -k | --public-key)
    readonly PUB_SSH_FILE="${2}"
    shift 2
    ;;
  -y | --yes)
    readonly YES='true'
    shift
    ;;
  --encrypt-home)
    readonly ENCRYPT_HOME='true'
    shift
    ;;
  --encrypt-root)
    readonly ENCRYPT_ROOT='true'
    shift
    ;;
  -p | --purge-all)
    readonly PURGE=true
    shift
    ;;
  -e | --efi | --uefi)
    readonly UEFI_FORCE=true
    shift
    ;;
  --uri)
    readonly URI="${2}"
    shift 2
    ;;
  --suite)
    readonly SUITE="${2}"
    shift 2
    ;;
  -b | --boot-size)
    BOOT_SIZE_B="$(numfmt --from=iec "${2}")"
    readonly BOOT_SIZE_B
    readonly BOOT_SIZE="${2}"
    shift 2
    ;;
  -r | --root-size)
    ROOT_SIZE_B="$(numfmt --from=iec "${2}")"
    readonly ROOT_SIZE_B
    readonly ROOT_SIZE="${2}"
    shift 2
    ;;
  -u | --home-size)
    HOME_SIZE_B="$(numfmt --from=iec "${2}")"
    readonly HOME_SIZE_B
    readonly HOME_SIZE="${2}"
    shift 2
    ;;
  -v | --var-size)
    VAR_SIZE_B="$(numfmt --from=iec "${2}")"
    readonly VAR_SIZE_B
    readonly VAR_SIZE="${2}"
    shift 2
    ;;
  --boot-part)
    readonly BOOT_PART="${2}"
    shift 2
    ;;
  --root-part)
    readonly ROOT_PART="${2}"
    shift 2
    ;;
  --home-part)
    readonly HOME_PART="${2}"
    shift 2
    ;;
  --var-part)
    readonly VAR_PART="${2}"
    shift 2
    ;;
  --raid)
    readonly RAID='true'
    shift
    ;;
  --skip-unmount)
    readonly SKIP_UNMOUNT='true'
    shift
    ;;
  --examples)
    examples
    ;;
  --raid-example)
    raid_example
    ;;
  -h | --help)
    usage
    ;;
  *)
    err_exit "unknown option '${key}'"
    ;;
  esac
done

if [[ ${ENCRYPT_ROOT} == 'true' ]]; then
  MAP_DEV="${LABEL_UNDER}_root_crypt"
elif [[ ${ENCRYPT_HOME} == 'true' ]]; then
  MAP_DEV="${LABEL_UNDER}_home_crypt"
fi

PART_ENC="/dev/mapper/${MAP_DEV}"


# tests and checks
# ================

if [[ -z "${IFACE}" ]]; then
    err_exit 'no network interface defined'
fi

if [[ -n "${STATIC_IP}" ]] && [[ -z "${STATIC_GW}" ]]; then
    err_exit 'both static ip and static gateway need to be defined'
fi

if [[ -z "${STATIC_IP}" ]] && [[ -n "${STATIC_GW}" ]]; then
    err_exit 'both static ip and static gateway need to be defined'
fi

if [[ -n "${STATIC_IP}" ]] && [[ ! "${STATIC_IP}" =~ .*/.* ]]; then
    err_exit 'static ip needs to have a netmask suffix defined'
fi

if [[ -n "${DEV}" ]]; then
  if [[ -n "${BOOT_PART}" ]] || [[ -n "${ROOT_PART}" ]]; then
    err_exit "can't define target device and root+boot partition paths"
  fi
fi

if [[ -z "${DEV}" ]]; then
  if [[ -z "${BOOT_PART}" ]] || [[ -z "${ROOT_PART}" ]]; then
    err_exit 'missing target device or root+boot partition paths'
  fi
else
  if [[ -n "${BOOT_PART}" ]] || [[ -n "${ROOT_PART}" ]]; then
    err_exit "either target device or root+boot partition paths must be defined"
  fi
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ ${ENCRYPT_HOME} == 'true' ]]; then
  err_exit "can't encrypt root and home at the same time"
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ -n ${HOME_PART} ]]; then
  err_exit "can't encrypt root and specify home partition at the same time"
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ -n ${HOME_SIZE} ]]; then
  err_exit "can't encrypt root and specify home partition at the same time"
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ -n ${VAR_PART} ]]; then
  err_exit "can't encrypt root and specify var partition at the same time"
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ -n ${VAR_SIZE} ]]; then
  err_exit "can't encrypt root and specify var partition at the same time"
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ ${YES} == 'true' ]]; then
  err_exit "can't encrypt and use yes at the same time"
fi

if [[ ${ENCRYPT_HOME} == 'true' ]] && [[ ${YES} == 'true' ]]; then
  err_exit "can't encrypt and use yes at the same time"
fi

if [[ ${ENCRYPT_ROOT} == 'true' ]] && [[ -e ${PART_ENC} ]]; then
  err_exit "encrypted partition ${PART_ENC} already exists"
fi

if [[ ${#LABEL} -gt 11 ]]; then
  err_exit "label can't be longer than 11 chars (with suffix _root limit is 16)"
fi

if [[ "${RAID}" == 'true' ]] && [[ "${UEFI_FORCE}" == 'false' ]]; then
  err_exit 'raid install requires uefi in this script'
fi

umask | grep -q '0022' || err_exit 'set umask to 0022'
stat -c '%a' /etc/resolv.conf | grep -q 644 \
  || err_exit 'set resolv.conf perms to 644'


# set variables
# =============

if [[ "${DEV}" =~ /dev/[sn].* ]]; then
  DEV_TYPE='device'

elif [[ -z "${DEV}" ]]; then
  dm=/dev/mapper/*
  if [[ "${BOOT_PART}" == ${dm} ]] && [[ "${ROOT_PART}" == ${dm} ]]; then
    DEV_TYPE='volume_group'
  elif [[ "${BOOT_PART}" == ${dm} ]] || [[ "${ROOT_PART}" == ${dm} ]]; then
    err_exit "both boot and root partitions need to be on '/dev/mapper/' path"
  else
    DEV_TYPE='device'
  fi
  unset dm

else
  if vgs "${DEV}" >/dev/null 2>&1; then
    DEV_TYPE='volume_group'
  else
    [[ -f "${DEV}" ]] && DEV_TYPE='file'
    [[ -d "${DEV}" ]] && DEV_TYPE='dir'
  fi
fi

SIZE="$(( BOOT_SIZE_B + ROOT_SIZE_B + HOME_SIZE_B + VAR_SIZE_B ))"
[[ "${DEV_TYPE}" == 'dir' ]] && ROOT_DIR="${DEV}"

# chroot command interpreter
CCMD="chroot ${ROOT_DIR} env -i DEBIAN_FRONTEND=noninteractive TERM=linux PATH=/usr/bin:/usr/sbin"

if [[ ${SUITE} == 'kali-last-snapshot' ]]; then
  KEYRING="${TMP_DIR}/usr/share/keyrings/kali-archive-keyring.gpg"
fi

[[ ${SUITE} == 'sid' ]] && SUITE='unstable'

# make sure that these global vars are readonly from now on
readonly DEV ROOT_DIR PUB_SSH_FILE ENCRYPT_HOME ENCRYPT_ROOT PURGE UEFI_FORCE \
  URI SUITE KEYRING BOOT_SIZE ROOT_SIZE HOME_SIZE VAR_SIZE SIZE \
  ROOT_DIR DEV_TYPE \
  UUID_GRUB UUID_BOOT UUID_BOOT_FAT UUID_ROOT UUID_HOME UUID_VAR


# tests and checks
# ================

command -v sgdisk >/dev/null || err_exit 'sgdisk from gdisk missing'
command -v partprobe  >/dev/null || err_exit 'partprobe from parted missing'
command -v debootstrap  >/dev/null || err_exit 'debootstrap missing'
command -v numfmt  >/dev/null || err_exit 'numfmt missing from coreutils'
command -v parted  >/dev/null || err_exit 'parted missing'
command -v mkfs.ext4  >/dev/null || err_exit 'mkfs.ext4 missing'
command -v perl  >/dev/null || err_exit 'perl missing from perl-base'

if [[ ! -e "${KEYRING}" ]]; then
  err_exit "${KEYRING} doesn't exist"
fi

mount -V | grep -q 'util-linux' \
  || err_exit 'mount command needs to be from util-linux, not busybox'

if [[ "${INST_TYPE}" == 'uefi' ]]; then
  command -v mkfs.fat  >/dev/null || err_exit 'mkfs.fat from dosfstools missing'
fi

if [[ "${DEV_TYPE}" != 'dir' ]]; then
  [[ -z "${BOOT_SIZE}" ]] && [[ -z "${BOOT_PART}" ]] \
    && err_exit 'boot partition not defined'
  [[ -z "${ROOT_SIZE}" ]] && [[ -z "${ROOT_PART}" ]] \
    && err_exit 'root partition not defined'
fi

[[ -z "${LABEL}" ]] && err_exit 'label prefix not defined'

label_exists='false'
blkid -s PARTLABEL -o value \
  | grep -q \
    -e ${LABEL}-grub \
    -e ${LABEL}-boot \
    -e ${LABEL}-root \
    -e ${LABEL}-home \
    -e ${LABEL}-var \
  && label_exists='true'

if [[ "${label_exists}" == 'true' ]]; then
  if [[ "${PURGE}" == 'true' ]] && [[ "${DEV_TYPE}" == 'device' ]]; then
    blkid -s PARTLABEL -o value ${DEV}* \
      | grep -q \
        -e ${LABEL}-grub \
        -e ${LABEL}-boot \
        -e ${LABEL}-root \
        -e ${LABEL}-home \
        -e ${LABEL}-var \
      || err_exit "label prefix '${LABEL}' already exists on a different disk"
  else
    err_exit "label prefix '${LABEL}' already exists - use purge"
  fi
fi
unset label_exists

findmnt "${ROOT_DIR}" && err_exit "${ROOT_DIR} already mounted"
[[ "${ROOT_DIR}" == '' ]] && err_exit 'ROOT_DIR is empty'
[[ "${ROOT_DIR}" == '/' ]] && err_exit '/ as ROOT_DIR not allowed'

if [[ "${DEV_TYPE}" == 'file' ]]; then
  command -v qemu-img >/dev/null || err_exit 'qemu-img from qemu-utils missing'
fi

if [[ "${DEV_TYPE}" == 'volume_group' ]] && [[ -n "${DEV}" ]]; then
  lvdisplay \
  | grep '  LV Name  ' \
  | grep -q \
    -e "${LABEL_UNDER}_grub" \
    -e "${LABEL_UNDER}_boot" \
    -e "${LABEL_UNDER}_root" \
    -e "${LABEL_UNDER}_home" \
    -e "${LABEL_UNDER}_var" \
  && err_exit "logical volumes with prefix '${LABEL_UNDER}' already exist"

  if [[ ${DEV} == *-* ]]; then
    err_exit "volume group name can't have a dash in it"
  fi

  if [[ ${DEV} == *_* ]]; then
    err_exit "volume group name can't have an underscore in it"
  fi

  if [[ ${PURGE} == 'true' ]]; then
    err_exit "can't purge a volume group, please remove it manually"
  fi
fi


# functions
# =========

get_free_space() {
  [[ "${DEV_TYPE}" == 'file' ]] && return
  [[ "${DEV_TYPE}" == 'dir' ]] && return
  [[ -z "${DEV}" ]] && return

  if [[ "${DEV_TYPE}" == 'device' ]]; then
    FREE_SPACE="$(parted "${DEV}" unit B print free \
      | grep 'Free Space' \
      | tail -n1 \
      | awk '{print $3}' \
      | tr -d 'B')"

  elif [[ "${DEV_TYPE}" == 'volume_group' ]]; then
    FREE_SPACE="$(vgs "${DEV}" --units=B --rows \
      | grep 'VFree ' \
      | awk '{print $2}' \
      | tr -d 'B')"
  fi

  if [[ -z "${FREE_SPACE}" ]]; then
    err_exit "target disk probably doesn't have partition table"
  fi

  if [[ "${FREE_SPACE}" -lt "${SIZE}" ]]; then
    err_exit "not enough unpartitioned space"
  fi

  readonly FREE_SPACE
}

get_kali_keyring() {
  local pkg
  pkg="$(curl -s http://http.kali.org/pool/main/k/kali-archive-keyring/ \
    | grep '"kali-archive-keyring_.*_all\.deb" ' \
    | cut -d'"' -f4)"
  mkdir -p ${TMP_DIR}
  wget -q "https://http.kali.org/pool/main/k/kali-archive-keyring/${pkg}" \
    -O "${TMP_DIR}/${pkg}"
  dpkg -x "${TMP_DIR}/${pkg}" ${TMP_DIR}/
}

partsync() {
  case "${DEV_TYPE}" in
  'file'|'device' )
    partprobe "${DEV}"
    ;;
  'volume_group' )
    partprobe "${BOOT_DISK}"
    ;;
  esac
  sleep 0.5
}

purge_partitions() {
  [[ "${DEV_TYPE}" == 'dir' ]] && return

  echo '+ purging existing partitions...'
  sgdisk --zap-all "${DEV}" && partsync
  dd if=/dev/zero of="${DEV}" bs=1M count=128 >/dev/null 2>&1
  sgdisk -g "${DEV}" && partsync
  sleep 0.5
}

get_partitions() {
  case "${DEV_TYPE}" in
  'device' )
    # find partition numbers to use only if partitions are not defined and the
    # device is defined
    if [[ -z "${DEV}" ]]; then
      INST_TYPE='uefi'
      return
    fi

    partsync
    local last_part
    last_part="$(sgdisk -p "${DEV}" \
      | sed -n '/^Number/,$p' \
      | tail -n +2 \
      | sort -n \
      | awk '{print $1}' \
      | tail -n1 \
      2> /dev/null)"

    if [[ -z "${last_part}" ]] || [[ "${PURGE}" == 'true' ]]; then
      last_part=0
      INST_TYPE='bios'
    else
      INST_TYPE='uefi'
    fi

    if [[ "${UEFI_FORCE}" == 'true' ]]; then
      INST_TYPE='uefi'
    fi

    # add 'p' in /dev/nvme partitions
    local disk_dev
    if [[ ${DEV} =~ /dev/nvme* ]]; then
      disk_dev="${DEV}p"
    else
      disk_dev="${DEV}"
    fi

    if [[ "${INST_TYPE}" == "bios" ]]; then
      GRUB_PART="${disk_dev}$((++last_part))"
      GRUB_PART_N="${last_part}"
    fi

    BOOT_PART="${disk_dev}$((++last_part))"
    BOOT_PART_N="${last_part}"

    ROOT_PART="${disk_dev}$((++last_part))"
    ROOT_PART_N="${last_part}"

    [[ -n "${HOME_SIZE}" ]] && HOME_PART="${disk_dev}$((++last_part))"
    [[ -n "${HOME_SIZE}" ]] && HOME_PART_N="${last_part}"

    [[ -n "${VAR_SIZE}" ]] && VAR_PART="${disk_dev}$((++last_part))"
    [[ -n "${VAR_SIZE}" ]] && VAR_PART_N="${last_part}"

    unset disk_dev
    ;;

  'volume_group' )
    INST_TYPE='bios'
    BOOT_DISK="/dev/mapper/${DEV}-${LABEL_UNDER}_boot"
    GRUB_PART="/dev/mapper/${DEV}-${LABEL_UNDER}_boot1"
    BOOT_PART="/dev/mapper/${DEV}-${LABEL_UNDER}_boot2"
    ROOT_PART="/dev/mapper/${DEV}-${LABEL_UNDER}_root"

    [[ -n "${HOME_SIZE}" ]] && HOME_PART="/dev/mapper/${DEV}-${LABEL_UNDER}_home"
    [[ -n "${VAR_SIZE}" ]] && VAR_PART="/dev/mapper/${DEV}-${LABEL_UNDER}_var"

    ;;

  'file' )
    INST_TYPE='bios'
    LOOP_DEV="$(losetup --find)"

    GRUB_PART="${LOOP_DEV}p1"
    GRUB_PART_N=1

    BOOT_PART="${LOOP_DEV}p2"
    BOOT_PART_N=2

    ROOT_PART="${LOOP_DEV}p3"
    ROOT_PART_N=3

    [[ -n "${HOME_SIZE}" ]] && HOME_PART="${LOOP_DEV}p4"
    [[ -n "${HOME_SIZE}" ]] && HOME_PART_N=4

    [[ -n "${VAR_SIZE}" ]] && VAR_PART="${LOOP_DEV}p5"
    [[ -n "${VAR_SIZE}" ]] && VAR_PART_N=5
    ;;
  esac

  # devices need to settle; without this next steps error out
  sleep 1
}

create_partitions() {
  [[ "${DEV_TYPE}" == 'dir' ]] && return
  [[ -z "${DEV}" ]] && return

  if [[ "${DEV_TYPE}" == 'volume_group' ]] && [[ -n "${DEV}" ]]; then
    echo '+ creating logical volumes...'

    lvcreate -y -W y -L "${BOOT_SIZE}" "${DEV}" -n "${LABEL_UNDER}_boot"
    lvcreate -y -W y -L "${ROOT_SIZE}" "${DEV}" -n "${LABEL_UNDER}_root"

    [[ -n "${HOME_SIZE}" ]] \
      && lvcreate -y -W y -L "${HOME_SIZE}" "${DEV}" -n "${LABEL_UNDER}_home"

    [[ -n "${VAR_SIZE}" ]] \
      && lvcreate -y -W y -L "${VAR_SIZE}" "${DEV}" -n "${LABEL_UNDER}_var"

    sleep 0.5
    lvscan > /dev/null

    echo '+ creating boot disk...'

    sgdisk --zap-all "${BOOT_DISK}" && partsync
    sgdisk -g "${BOOT_DISK}" && partsync

    sgdisk --new "1::+2M" -u "1:${UUID_GRUB}" "${BOOT_DISK}" && partsync
    sgdisk -t "1:ef02" "${BOOT_DISK}" && partsync
    sgdisk -c "1:${LABEL}-grub" "${BOOT_DISK}" && partsync

    sgdisk --new "2:+2M:" -u "2:${UUID_BOOT}" "${BOOT_DISK}" && partsync
    sgdisk --attributes "2:set:2" "${BOOT_DISK}" && partsync
    sgdisk -c "2:${LABEL}-boot" "${BOOT_DISK}" && partsync

    return
  fi

  if [[ "${DEV_TYPE}" == 'file' ]]; then
    echo '+ preparing vm file...'
    qemu-img create -f raw "${DEV}" "$(( SIZE + 10*1024*1024 ))"
    sgdisk -g "${DEV}" && partsync
  fi

  if [[ "${DEV_TYPE}" == 'device' ]]; then
    if gdisk -l "${DEV}" | grep -q 'GPT: not present'; then
      echo "+ creating gpt partition table on ${DEV}..."
      sgdisk -g "${DEV}"
      partsync
    fi
  fi

  partsync

  if [[ "${INST_TYPE}" == 'bios' ]]; then
    echo '+ creating grub partition...'
    sgdisk --new "${GRUB_PART_N}::+2M" \
      -u "${GRUB_PART_N}:${UUID_GRUB}" "${DEV}" && partsync

    # mark the grub partition as BIOS boot partition
    sgdisk -t "${GRUB_PART_N}:ef02" "${DEV}" && partsync

    # name the grub partition
    sgdisk -c "${GRUB_PART_N}:${LABEL}-grub" "${DEV}" && partsync
  fi

  echo '+ creating boot partition...'
  sgdisk --new "${BOOT_PART_N}:+2M:+${BOOT_SIZE}" \
    -u "${BOOT_PART_N}:${UUID_BOOT}" "${DEV}" && partsync

  if [[ "${INST_TYPE}" == 'bios' ]]; then
    # set legacy bios bootable attribute on boot device;
    # grub ignores it, but syslinux does not
    sgdisk --attributes "${BOOT_PART_N}:set:2" "${DEV}" && partsync

  elif [[ "${INST_TYPE}" == 'uefi' ]]; then
    # mark the boot partition as EFI system partition
    sgdisk -t "${BOOT_PART_N}:ef00" "${DEV}" && partsync
  fi

  # name the boot partition
  sgdisk -c "${BOOT_PART_N}:${LABEL}-boot" "${DEV}" && partsync


  echo '+ creating root partition...'
  sgdisk --new "${ROOT_PART_N}::+${ROOT_SIZE}" \
    -u "${ROOT_PART_N}:${UUID_ROOT}" "${DEV}" && partsync

  # name the root partition
  sgdisk -c "${ROOT_PART_N}:${LABEL}-root" "${DEV}" && partsync

  if [[ ${ENCRYPT_ROOT} == 'false' ]]; then
    # mark the root partition as linux filesystem
    sgdisk -t "${ROOT_PART_N}:8300" "${DEV}" && partsync
  else
    # mark the root partition as linux luks partition
    sgdisk -t "${ROOT_PART_N}:8309" "${DEV}" && partsync
  fi

  if [[ -n "${HOME_SIZE}" ]]; then
    echo '+ creating home partition...'
    sgdisk --new "${HOME_PART_N}::+${HOME_SIZE}" \
      -u "${HOME_PART_N}:${UUID_HOME}" "${DEV}" && partsync
    sgdisk -t "${HOME_PART_N}:8300" "${DEV}" && partsync
    sgdisk -c "${HOME_PART_N}:${LABEL}-home" "${DEV}" && partsync
  fi

  if [[ -n "${VAR_SIZE}" ]]; then
    echo '+ creating var partition...'
    sgdisk --new "${VAR_PART_N}::+${VAR_SIZE}" \
      -u "${VAR_PART_N}:${UUID_VAR}" "${DEV}" && partsync
    sgdisk -t "${VAR_PART_N}:8300" "${DEV}" && partsync
    sgdisk -c "${VAR_PART_N}:${LABEL}-var" "${DEV}" && partsync
  fi

  if [[ "${DEV_TYPE}" == 'file' ]]; then
    losetup -Pf "${DEV}"
  fi

  sleep 0.5
}

create_filesystems() {
  [[ "${DEV_TYPE}" == 'dir' ]] && return

  echo '+ creating boot filesystem...'
  if [[ "${INST_TYPE}" == 'bios' ]]; then
    mkfs.ext4 -F -L "${LABEL}-boot" -U "${UUID_BOOT}" "${BOOT_PART}"

  elif [[ "${INST_TYPE}" == 'uefi' ]]; then
    mkfs.fat -i "${UUID_BOOT_FAT}" -n "${LABEL}-boot" -F32 "${BOOT_PART}"
  fi

  if [[ ${ENCRYPT_ROOT} == 'false' ]]; then
    echo '+ creating root filesystem...'
    mkfs.ext4 -F -L "${LABEL}-root" -U "${UUID_ROOT}" "${ROOT_PART}"
  fi

  if [[ -n "${HOME_SIZE}" ]] || [[ -n "${HOME_PART}" ]]; then
    echo '+ creating home filesystem...'
    if [[ ${ENCRYPT_HOME} == 'false' ]]; then
      mkfs.ext4 -F -L "${LABEL}-home" -U "${UUID_HOME}" "${HOME_PART}"
    elif [[ ${ENCRYPT_HOME} == 'true' ]]; then
      cryptsetup -v \
        --type luks2 \
        --cipher aes-xts-plain64 \
        --pbkdf argon2id \
        --hash sha512 \
        --key-size 512 \
        --iter-time 5000 \
        --batch-mode \
        --uuid="${UUID_HOME}" \
        luksFormat "${HOME_PART}"
      echo 'Enter the password again to mount encrypted home...'
      cryptsetup luksOpen --allow-discards "${HOME_PART}" ${MAP_DEV}
      mkfs.ext4 -F -L "${LABEL}-home" -U "${UUID_HOME}" "${PART_ENC}"
    fi
  fi

  if [[ ${ENCRYPT_ROOT} == 'true' ]]; then
    cryptsetup -v \
      --type luks2 \
      --cipher aes-xts-plain64 \
      --pbkdf argon2id \
      --hash sha512 \
      --key-size 512 \
      --iter-time 5000 \
      --batch-mode \
      --uuid="${UUID_ROOT}" \
      luksFormat "${ROOT_PART}"
    echo 'Enter the password again to mount encrypted root...'
    cryptsetup luksOpen --allow-discards "${ROOT_PART}" ${MAP_DEV}
    mkfs.ext4 -F -L "${MAP_DEV}" -U "${UUID_ROOT}" "${PART_ENC}"
  fi
      #--pbkdf pbkdf2 \

  if [[ -n "${VAR_SIZE}" ]] || [[ -n "${VAR_PART}" ]]; then
    echo '+ creating var filesystem...'
    mkfs.ext4 -F -L "${LABEL}-var" -U "${UUID_VAR}" "${VAR_PART}"
  fi
}

mount_partitions() {
  [[ "${DEV_TYPE}" == 'dir' ]] && return

  echo '+ mounting partitions...'
  mkdir -p "${ROOT_DIR}"

  if [[ "${ENCRYPT_ROOT}" == true ]]; then
    mount -o sync "${PART_ENC}" "${ROOT_DIR}"
  else
    mount -o sync "${ROOT_PART}" "${ROOT_DIR}"
  fi

  mkdir -p ${ROOT_DIR}/{boot,home,var}
  mount -o sync "${BOOT_PART}" "${ROOT_DIR}/boot"

  if [[ -n "${HOME_SIZE}" ]] || [[ -n "${HOME_PART}" ]]; then
    if [[ "${ENCRYPT_HOME}" == true ]]; then
      mount -o sync "${PART_ENC}" "${ROOT_DIR}/home"
    else
      mount -o sync "${HOME_PART}" "${ROOT_DIR}/home"
    fi
  fi

  if [[ -n "${VAR_SIZE}" ]] || [[ -n "${VAR_PART}" ]]; then
    mount -o sync "${VAR_PART}" "${ROOT_DIR}/var"
  fi
}

set_fstab() {
  [[ "${DEV_TYPE}" == 'dir' ]] && return

  echo '+ configuring fstab...'

  cat > ${ROOT_DIR}/etc/fstab << EOF
proc   /proc     proc   rw,nosuid,nodev,noexec,hidepid=2,gid=0 0 0
sys    /sys      sysfs  rw,nosuid,nodev,noexec                 0 0
run    /run      tmpfs  rw,nosuid,nodev,mode=0755              0 0
tmp    /tmp      tmpfs  rw,nosuid,nodev,mode=0777,size=80%     0 0

shm    /dev/shm  tmpfs  rw,nosuid,noexec,mode=1777             0 0
devpts /dev/pts  devpts rw,nosuid,noexec,mode=0620,gid=5       0 0
lock   /run/lock tmpfs  rw,nosuid,nodev,noexec,mode=1777       0 0
EOF

  if [[ "${RAID}" == 'true' ]]; then
    ${CCMD} apt-get -y install mdadm
    echo '/dev/md/root  /        ext4   rw,lazytime,noiversion  0 1' \
      >> ${ROOT_DIR}/etc/fstab
    echo '/dev/md/boot  /boot    vfat   rw,sync,noiversion      0 2' \
      >> ${ROOT_DIR}/etc/fstab

    if [[ -n "${HOME_PART}" ]]; then
      echo '/dev/md/home  /home    ext4   rw,lazytime,noiversion  0 2' \
        >> ${ROOT_DIR}/etc/fstab
    fi

    if [[ -n "${VAR_PART}" ]]; then
      echo '/dev/md/var   /var     ext4   rw,lazytime,noiversion  0 2' \
        >> ${ROOT_DIR}/etc/fstab
    fi

    return
  fi

  local uuid_boot
  local boot_fs_type='ext4'

  if [[ "${INST_TYPE}" == 'bios' ]]; then
    uuid_boot="${UUID_BOOT}"

  elif [[ "${INST_TYPE}" == 'uefi' ]]; then
    uuid_boot="${UUID_BOOT_FAT^^}"
    uuid_boot="${uuid_boot:0:4}-${uuid_boot:4:8}"
    boot_fs_type='vfat'
  fi

  if [[ "${ENCRYPT_ROOT}" == true ]]; then
    echo "${PART_ENC}        /      ext4  rw,lazytime,noiversion  0 1" >> ${ROOT_DIR}/etc/fstab
  else
    echo "UUID=${UUID_ROOT}  /      ext4  rw,lazytime,noiversion  0 1" >> ${ROOT_DIR}/etc/fstab
  fi

  echo "UUID=${uuid_boot}  /boot  ${boot_fs_type}  rw,sync,noiversion      0 2" >> ${ROOT_DIR}/etc/fstab

  if [[ -n "${HOME_SIZE}" ]] && [[ "${ENCRYPT_HOME}" == 'false' ]]; then
    echo "UUID=${UUID_HOME}  /home  ext4  rw,lazytime,noiversion  0 2" \
      >> ${ROOT_DIR}/etc/fstab
  fi

  if [[ -n "${VAR_SIZE}" ]]; then
    echo "UUID=${UUID_VAR}  /var   ext4  rw,lazytime,noiversion  0 2" \
      >> ${ROOT_DIR}/etc/fstab
  fi
}

set_timezone() {
  echo '+ configuring timezone...'
  ${CCMD} debconf-set-selections << EOF
tzdata tzdata/Areas select Europe
tzdata tzdata/Zones/Europe select Warsaw
EOF

  ${CCMD} rm -f /etc/localtime /etc/timezone
  ${CCMD} DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure -f noninteractive tzdata
}

set_network() {
  echo '+ configuring network...'

  cat > ${ROOT_DIR}/etc/network/interfaces << EOF
auto lo
iface lo inet loopback
iface lo inet6 loopback
source /etc/network/interfaces.d/*
EOF

  if [[ ${STATIC_IP} == '' ]]; then

    # network config for dhcp
    cat > ${ROOT_DIR}/etc/network/interfaces.d/${IFACE} << EOF
auto ${IFACE}
iface ${IFACE} inet dhcp
iface ${IFACE} inet6 auto
  dns-nameservers 9.9.9.9
EOF

  else

    # network config for static ip
    cat > ${ROOT_DIR}/etc/network/interfaces.d/${IFACE} << EOF
auto ${IFACE}
iface ${IFACE} inet static
  address ${STATIC_IP}
  gateway ${STATIC_GW}
EOF

    if [[ ${DNS_SERVER} == '' ]]; then
      cat > ${ROOT_DIR}/etc/resolv.conf << EOF
nameserver ${STATIC_GW}
EOF
    else
      cat > ${ROOT_DIR}/etc/resolv.conf << EOF
nameserver ${DNS_SERVER}
EOF
    fi
  fi

  cat > ${ROOT_DIR}/etc/hosts << EOF
127.0.0.1       localhost local debian
EOF
}

set_apt() {
  echo '+ configuring apt...'

  if [[ ${SUITE} == 'kali-last-snapshot' ]]; then
    cat > ${ROOT_DIR}/etc/apt/sources.list << EOF
deb http://http.kali.org/kali kali-rolling ${APT_REPOS}
EOF
  elif [[ ${SUITE} == 'unstable' ]]; then
    cat > ${ROOT_DIR}/etc/apt/sources.list << EOF
deb http://deb.debian.org/debian ${SUITE} ${APT_REPOS}
EOF
  else
    cat > ${ROOT_DIR}/etc/apt/sources.list << EOF
deb http://deb.debian.org/debian ${SUITE} ${APT_REPOS}
deb http://deb.debian.org/debian-security/ ${SUITE}-security ${APT_REPOS}
deb http://deb.debian.org/debian ${SUITE}-updates ${APT_REPOS}
EOF
  fi

  cat > ${ROOT_DIR}/etc/apt/apt.conf.d/99norecommend << EOF
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF

  ${CCMD} apt-get -o 'APT::Update::Error-Mode=any' update

  if [[ ${SUITE} == 'kali-last-snapshot' ]]; then
    ${CCMD} apt-get dist-upgrade -y
    sleep 1
    ${CCMD} apt-get install -y ca-certificates
  fi
}

set_locale() {
  echo '+ configuring locale...'
  ${CCMD} apt-get install -y locales
  ${CCMD} debconf-set-selections << EOF
locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8, pl_PL.UTF-8 UTF-8
locales locales/default_environment_locale select en_US.UTF-8
EOF

  ${CCMD} rm -f /etc/default/locale /etc/locale.gen
  ${CCMD} DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure -f noninteractive locales
}

set_keyboard() {
  echo '+ configuring keyboard...'
  ${CCMD} apt-get install -y keyboard-configuration
  ${CCMD} debconf-set-selections << EOF
keyboard-configuration keyboard-configuration/layoutcode string pl
keyboard-configuration keyboard-configuration/xkb-keymap string pl
EOF

  ${CCMD} rm -f /etc/default/keyboard
  ${CCMD} DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure -f noninteractive keyboard-configuration
}

install_bootloader() {
  [[ "${DEV_TYPE}" == 'dir' ]] && return

  echo '+ installing grub...'
  local dev
  case "${DEV_TYPE}" in
  'device'       ) dev=${DEV} ;;
  'volume_group' ) dev=${BOOT_DISK} ;;
  'file'         ) dev=${LOOP_DEV} ;;
  esac

  if [[ "${INST_TYPE}" == 'bios' ]]; then
    ${CCMD} apt-get -y install grub2
    ${CCMD} grub-install --target=i386-pc ${dev} --locales=

  elif [[ "${INST_TYPE}" == 'uefi' ]]; then
    if [[ "${RAID}" == 'false' ]]; then
      ${CCMD} apt-get -y install grub-efi-amd64
      ${CCMD} grub-install --efi-directory=/boot --target=x86_64-efi \
        --locales= --bootloader-id=debian
    else
      ${CCMD} apt-get -y install grub-efi-amd64 mdadm efibootmgr
      ${CCMD} grub-install --efi-directory=/boot --target=x86_64-efi \
        --locales= --no-nvram
    fi
  fi

  # default linux cmdline parameters for grub
  local p
  if [[ "${RAID}" == 'true' ]]; then
    p="root=/dev/md/root"
  elif [[ "${ENCRYPT_ROOT}" == 'true' ]]; then
    p="root=LABEL=${MAP_DEV}"
  else
    p="root=LABEL=${LABEL}-root"
  fi

  if [[ "${DEV_TYPE}" == 'device' ]]; then
    p+=' console=tty0'
  else
    p+=' nomodeset console=ttyS0,115200n8'
  fi

  if [[ "${ENCRYPT_ROOT}" == true ]]; then
    echo "${MAP_DEV} PARTLABEL=${LABEL}-root none luks" > ${ROOT_DIR}/etc/crypttab
    ${CCMD} apt-get -y install cryptsetup-initramfs
  fi

  sed -i \
    -e 's|^#GRUB_DISABLE_LINUX_UUID=|GRUB_DISABLE_LINUX_UUID=|' \
    -e 's|^#GRUB_TERMINAL=|GRUB_TERMINAL=|' \
    -e "s|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT='$p'|" \
    ${ROOT_DIR}/etc/default/grub

  ${CCMD} update-grub

  if [[ "${RAID}" == 'true' ]]; then
    echo '+ adding uefi entries...'

    devices="$(mdadm --detail -Y /dev/md/boot | grep MD_DEVICE.*DEV= \
      | cut -d= -f2 | cut -d/ -f3)"

    for dev in ${devices}; do
      efibootmgr -v -c -d "/dev/$(lsblk -o pkname -d -n /dev/${dev})" -p 1 \
        -l '\EFI\debian\grubx64.efi' -L ${LABEL}_${dev} \
        --unicode --full-dev-path
    done

    sed -i "s|^HOMEHOST .*|HOMEHOST = ${LABEL}|" ${ROOT_DIR}/etc/mdadm/mdadm.conf

    unset dev devices
  fi

  ${CCMD} update-initramfs -u
}

sys_config() {
  ${CCMD} sh -c 'echo root:root | chpasswd'

  sed -i 's|^#PermitRootLogin|PermitRootLogin|' ${ROOT_DIR}/etc/ssh/sshd_config
  rm ${ROOT_DIR}/etc/ssh/ssh_host_{ecdsa,rsa}_key*

  mkdir ${ROOT_DIR}/etc/systemd/system/getty@.service.d
  echo -e '[Service]\nTTYVTDisallocate=no' > ${ROOT_DIR}/etc/systemd/system/getty@.service.d/noclear.conf

  echo "${LABEL}" > ${ROOT_DIR}/etc/hostname
}

pkg_install() {
  ${CCMD} apt-get install -y python3

  if [[ "${DEV_TYPE}" != 'dir' ]] && [[ ${DEV_TYPE} != 'device' ]]; then
    ${CCMD} apt-get install -y acpid
  fi

  [[ ${ENCRYPT_HOME} == 'true' ]] && ${CCMD} apt-get install -y cryptsetup

  ${CCMD} systemctl enable ssh
  ${CCMD} apt-get clean
}

deploy_ssh_key() {
  [[ -z ${PUB_SSH_FILE} ]] && return

  mkdir -p ${ROOT_DIR}/root/.ssh
  chmod 700 ${ROOT_DIR}/root/.ssh
  cat ${PUB_SSH_FILE} > ${ROOT_DIR}/root/.ssh/authorized_keys
}

unmount() {
  if [[ "{SKIP_UNMOUNT}" == 'true' ]]; then
    echo '+ skipping unmount.'
    return
  fi

  echo '+ unmounting...'

  echo 'unmounting virtual filesystems...'
  if [[ "${INST_TYPE}" == 'uefi' ]]; then
    ${CCMD} umount /sys/firmware/efi/efivars
  fi
  umount ${ROOT_DIR}/dev/pts && sleep 0.1
  umount ${ROOT_DIR}/{dev,sys} && sleep 0.1
  umount ${ROOT_DIR}/var/tmp && sleep 0.1

  if [[ -n "${HOME_SIZE}" ]] || [[ -n "${HOME_PART}" ]]; then
    echo 'unmounting /home...'
    umount ${ROOT_DIR}/home && sleep 0.1
  fi

  if [[ -n "${VAR_SIZE}" ]] || [[ -n "${VAR_PART}" ]]; then
    echo 'unmounting /var...'
    umount ${ROOT_DIR}/var && sleep 0.1
  fi

  if [[ "${DEV_TYPE}" != 'dir' ]]; then
    echo 'unmounting /boot...'
    umount  ${ROOT_DIR}/boot && sleep 0.1
  fi

  echo 'unmounting /proc...'
  umount ${ROOT_DIR}/proc && sleep 0.1

  echo 'unmounting root...'
  if [[ "${DEV_TYPE}" != 'dir' ]]; then
    umount  ${ROOT_DIR}/ && sleep 0.1
  fi

  if [[ "${ENCRYPT_ROOT}" == 'true' ]]; then
    echo 'closing root luks device...'
    cryptsetup luksClose ${MAP_DEV} && sleep 0.1
  fi

  if [[ "${ENCRYPT_HOME}" == 'true' ]]; then
    echo 'closing home luks device...'
    cryptsetup luksClose ${MAP_DEV} && sleep 0.1
  fi

  if [[ "${DEV_TYPE}" == 'file' ]]; then
    echo 'removing loop device...'
    losetup -d "${LOOP_DEV}" && sleep 0.1
  fi

  echo 'done unmounting.'
}


# confirmation
# ============

get_partitions

# get free space info early if we're not purging
if [[ "${PURGE}" == 'false' ]]; then
  get_free_space
fi

echo -e "target device/file   ${DEV}
device type          ${DEV_TYPE}
install type         ${INST_TYPE}

grub partition       ${GRUB_PART}
boot partition       ${BOOT_PART}
root partition       ${ROOT_PART}
home partition       ${HOME_PART}
var partition        ${VAR_PART}

boot size            ${BOOT_SIZE}
root size            ${ROOT_SIZE}
home size            ${HOME_SIZE}
var size             ${VAR_SIZE}

install size         $(numfmt --to=iec-i --suffix=B --format="%.2f" ${SIZE})"

if [[ "${DEV_TYPE}" == 'device' ]] && [[ -n "${DEV}" ]] && [[ ${PURGE} == 'false' ]]; then
  echo -n "free space           "
  numfmt --to='iec-i' --suffix='B' --format='%.2f' ${FREE_SPACE}
fi

if [[ "${DEV_TYPE}" == 'volume_group' ]] && [[ -n "${DEV}" ]]; then
  echo -n 'free space           '
  numfmt --to='iec-i' --suffix='B' --format='%.2f' ${FREE_SPACE}
fi

if [[ "${PURGE}" == 'true' ]]; then
  echo -e "\nWARNING: This ${DEV_TYPE} is going to be wiped:\n${DEV}"
fi

echo -e '\nexisting disk layout:'
if [[ -b "${DEV}" ]]; then
  lsblk -o NAME,SIZE,FSUSED,TYPE,FSTYPE,MOUNTPOINT "${DEV}" \
    | tail -n +2
fi

if [[ ${YES} == 'false' ]]; then
  printf "\nPress 'Ctrl+c' to abort or 'Enter' to continue..."
  read
fi


# main
# ====

if [[ ${SUITE} == 'kali-last-snapshot' ]]; then
  get_kali_keyring
fi

if [[ "${PURGE}" == 'true' ]]; then
  purge_partitions
  get_free_space
fi

# make sure that these global vars are readonly from now on
readonly BOOT_PART ROOT_PART HOME_PART VAR_PART LOOP_DEV INST_TYPE

if [[ -n "${BOOT_PART}" ]] && [[ -n "${ROOT_PART}" ]]; then
  create_partitions
fi

create_filesystems
mount_partitions

echo '+ installing...'
debootstrap \
  --arch amd64 \
  --include=vim,openssh-server,bridge-utils,dbus \
  --keyring=${KEYRING} \
  ${SUITE} ${ROOT_DIR} ${URI}

mount --bind /dev ${ROOT_DIR}/dev
mount --bind /dev/pts ${ROOT_DIR}/dev/pts
mount --bind /proc ${ROOT_DIR}/proc
mount --bind /sys ${ROOT_DIR}/sys
mount --types tmpfs tmpfs ${ROOT_DIR}/var/tmp
if [[ "${INST_TYPE}" == 'uefi' ]]; then
  ${CCMD} mount -t efivarfs none /sys/firmware/efi/efivars
fi

set_fstab
set_timezone
set_network
set_apt
set_locale
set_keyboard

if [[ "${DEV_TYPE}" != 'dir' ]]; then
  echo '+ installing kernel...'
  ${CCMD} apt-get -y --no-install-recommends install linux-image-amd64 zstd
fi

install_bootloader
sys_config
pkg_install
deploy_ssh_key
unmount

rm -rf ${TMP_DIR}
sync
echo '+ done'

